!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitgencellside(f2pysetupfunc)
      use gencellside, only : ncl
      use gencellside, only : nfc
      use gencellside, only : dx
      use gencellside, only : dy
      use gencellside, only : dxr
      use gencellside, only : dyr
      use gencellside, only : chg
      use gencellside, only : nu
      use gencellside, only : nv
      use gencellside, only : nc
      use gencellside, only : ns
      use gencellside, only : nt
      use gencellside, only : n9
      use gencellside, only : n8
      use gencellside, only : n4
      use gencellside, only : n2
      use gencellside, only : n1
      use gencellside, only : ice
      use gencellside, only : kg
      use gencellside, only : isd
      use gencellside, only : jsd
      use gencellside, only : i
      use gencellside, only : ii
      use gencellside, only : ij
      use gencellside, only : ijk
      use gencellside, only : j
      use gencellside, only : jj
      use gencellside, only : jk
      use gencellside, only : jkl
      use gencellside, only : k
      use gencellside, only : kk
      use gencellside, only : kl
      use gencellside, only : klm
      use gencellside, only : l
      use gencellside, only : ll
      use gencellside, only : lm
      use gencellside, only : lmn
      use gencellside, only : m
      use gencellside, only : mm
      use gencellside, only : mn
      use gencellside, only : n
      use gencellside, only : nn
      use gencellside, only : nlat
      use gencellside, only : nlon
      use gencellside, only : xext
      use gencellside, only : rundate
      use gencellside, only : adapgrid
      use gencellside, only : cellside
      external f2pysetupfunc
      call f2pysetupfunc(ncl,nfc,dx,dy,dxr,dyr,chg,nu,nv,nc,ns,nt,n9,n8,&
     &n4,n2,n1,ice,kg,isd,jsd,i,ii,ij,ijk,j,jj,jk,jkl,k,kk,kl,klm,l,ll,l&
     &m,lmn,m,mm,mn,n,nn,nlat,nlon,xext,rundate,adapgrid,cellside)
      end subroutine f2pyinitgencellside


